const services = [
  {
    id: 1,
    title: "Carpet Cleaning",
    description: "Professional steam cleaning to remove deep dirt and stubborn stains from your carpets.",
    cost: "$100",
    imageSrc: "/images/carpet-cleaning.webp",
    slug: "carpet-cleaning", // Slug para la URL dinámica
  },
  {
    id: 2,
    title: "Upholstery Cleaning",
    description: "Expert cleaning for sofas, chairs, and other upholstered furniture.",
    cost: "$90",
    imageSrc: "/images/upholstery-cleaning.webp",
    slug: "upholstery-cleaning",
  },
  {
    id: 3,
    title: "Area Rug Cleaning",
    description: "Delicate cleaning for area rugs, ensuring colors and fibers are protected.",
    cost: "$75",
    imageSrc: "/images/cleaning-process.webp",
    slug: "area-rug-cleaning",
  },
  {
    id: 4,
    title: "Tile and Grout Cleaning",
    description: "Steam cleaning to remove grime and restore the shine of tile and grout.",
    cost: "$120",
    imageSrc: "/images/tile-grout-cleaning.webp",
    slug: "tile-and-grout-cleaning",
  },
  {
    id: 5,
    title: "Hotel - Corridors and Hallways",
    description: "Professional steam cleaning to remove deep dirt and stubborn stains from your carpets.",
    cost: "$85",
    imageSrc: "/images/Hotel-Corridors-and-Hallways.webp",
    slug: "hotel-corridors-hallways",
  },
  {
    id: 6,
    title: "Arm Chair Guard",
    description: "Specialized treatments to remove odors from your chairs.",
    cost: "$110",
    imageSrc: "/images/Arm-Chair-Guard.webp",
    slug: "arm-chair-guard",
  },
  {
    id: 7,
    title: "Outdoor Furnitures",
    description: "Emergency steam cleaning for water-damaged Outdoor Furnitures.",
    cost: "$200",
    imageSrc: "/images/outdoor-furnitures.webp",
    slug: "outdoor-furnitures",
  },
  {
    id: 8,
    title: "Commercial Carpet Cleaning",
    description: "Keep your office carpets looking professional and clean with our commercial services.",
    cost: "$300",
    imageSrc: "/images/Commercial Carpet Cleaning.webp",
    slug: "commercial-carpet-cleaning",
  },
  {
    id: 9,
    title: "Mattress Cleaning Different Sizes",
    description: "Advanced treatments for removing deep, stubborn stains from beds.",
    cost: "$175",
    imageSrc: "/images/mattress-removal.webp",
    slug: "mattress-cleaning",
  },
  {
    id: 10,
    title: "Recliner Couches",
    description: "Steam cleaning for your vehicle's interior carpets and upholstery.",
    cost: "$70",
    imageSrc: "/images/recliner-couches.webp",
    slug: "recliner-couches",
  },
  {
    id: 11,
    title: "Hardwood Floor Cleaning",
    description: "Steam cleaning to refresh and sanitize your hardwood floors.",
    cost: "$150",
    imageSrc: "/images/hardwood-floor-cleaning.jpg",
    slug: "hardwood-floor-cleaning",
  },
  {
    id: 12,
    title: "Drapery Cleaning",
    description: "Gentle steam cleaning for curtains and drapes, removing dust and allergens.",
    cost: "$95",
    imageSrc: "/images/drapery-cleaning.jpg",
    slug: "drapery-cleaning",
  },
];

export default services;
